next_button_map_0 = {
    1: {
        "U": None,
        "D": 4,
        "L": None,
        "R": 2
    },
    2: {
        "U": None,
        "D": 5,
        "L": 1,
        "R": 3
    },
    3: {
        "U": None,
        "D": 6,
        "L": 2,
        "R": None
    },
    4: {
        "U": 1,
        "D": 7,
        "L": None,
        "R": 5
    },
    5: {
        "U": 2,
        "D": 8,
        "L": 4,
        "R": 6
    },
    6: {
        "U": 3,
        "D": 9,
        "L": 5,
        "R": None
    },
    7: {
        "U": 4,
        "D": None,
        "L": None,
        "R": 8
    },
    8: {
        "U": 5,
        "D": None,
        "L": 7,
        "R": 9
    },
    9: {
        "U": 6,
        "D": None,
        "L": 8,
        "R": None
    }
}

next_button_map_1 = {
    '1': {
        "U": None,
        "D": '3',
        "L": None,
        "R": None
    },
    '2': {
        "U": None,
        "D": '6',
        "L": None,
        "R": '3'
    },
    '3': {
        "U": '1',
        "D": '7',
        "L": '2',
        "R": '4'
    },
    '4': {
        "U": None,
        "D": '8',
        "L": '3',
        "R": None
    },
    '5': {
        "U": None,
        "D": None,
        "L": None,
        "R": '6'
    },
    '6': {
        "U": '2',
        "D": 'A',
        "L": '5',
        "R": '7'
    },
    '7': {
        "U": '3',
        "D": 'B',
        "L": '6',
        "R": '8'
    },
    '8': {
        "U": '4',
        "D": 'C',
        "L": '7',
        "R": '9'
    },
    '9': {
        "U": None,
        "D": None,
        "L": '8',
        "R": None
    },
    'A': {
        "U": '6',
        "D": None,
        "L": None,
        "R": 'B'
    },
    'B': {
        "U": '7',
        "D": 'D',
        "L": 'A',
        "R": 'C'
    },
    'C': {
        "U": '8',
        "D": None,
        "L": 'B',
        "R": None
    },
    'D': {
        "U": 'B',
        "D": None,
        "L": None,
        "R": None
    }                            
}

def get_code(next_button_map, inputs):
    code = []
    button = '5'
    for input in inputs:
        for x in input:
            next_button = next_button_map[button][x]
            if next_button:
                button = next_button
        code.append(button)
    return code

INPUTS = [
"LURLDDLDULRURDUDLRULRDLLRURDUDRLLRLRURDRULDLRLRRDDULUDULURULLURLURRRLLDURURLLUURDLLDUUDRRDLDLLRUUDURURRULURUURLDLLLUDDUUDRULLRUDURRLRLLDRRUDULLDUUUDLDLRLLRLULDLRLUDLRRULDDDURLUULRDLRULRDURDURUUUDDRRDRRUDULDUUULLLLURRDDUULDRDRLULRRRUUDUURDULDDRLDRDLLDDLRDLDULUDDLULUDRLULRRRRUUUDULULDLUDUUUUDURLUDRDLLDDRULUURDRRRDRLDLLURLULDULRUDRDDUDDLRLRRDUDDRULRULULRDDDDRDLLLRURDDDDRDRUDUDUUDRUDLDULRUULLRRLURRRRUUDRDLDUDDLUDRRURLRDDLUUDUDUUDRLUURURRURDRRRURULUUDUUDURUUURDDDURUDLRLLULRULRDURLLDDULLDULULDDDRUDDDUUDDUDDRRRURRUURRRRURUDRRDLRDUUULLRRRUDD",
"DLDUDULDLRDLUDDLLRLUUULLDURRUDLLDUDDRDRLRDDUUUURDULDULLRDRURDLULRUURRDLULUDRURDULLDRURUULLDLLUDRLUDRUDRURURUULRDLLDDDLRUDUDLUDURLDDLRRUUURDDDRLUDDDUDDLDUDDUUUUUULLRDRRUDRUDDDLLLDRDUULRLDURLLDURUDDLLURDDLULLDDDRLUDRDDLDLDLRLURRDURRRUDRRDUUDDRLLUDLDRLRDUDLDLRDRUDUUULULUDRRULUDRDRRLLDDRDDDLULURUURULLRRRRRDDRDDRRRDLRDURURRRDDULLUULRULURURDRRUDURDDUURDUURUURUULURUUDULURRDLRRUUDRLLDLDRRRULDRLLRLDUDULRRLDUDDUUURDUDLDDDUDL",
"RURDRUDUUUUULLLUULDULLLDRUULURLDULULRDDLRLLRURULLLLLLRULLURRDLULLUULRRDURRURLUDLULDLRRULRDLDULLDDRRDLLRURRDULULDRRDDULDURRRUUURUDDURULUUDURUULUDLUURRLDLRDDUUUUURULDRDUDDULULRDRUUURRRDRLURRLUUULRUDRRLUDRDLDUDDRDRRUULLLLDUUUULDULRRRLLRLRLRULDLRURRLRLDLRRDRDRLDRUDDDUUDRLLUUURLRLULURLDRRULRULUDRUUURRUDLDDRRDDURUUULLDDLLDDRUDDDUULUDRDDLULDDDDRULDDDDUUUURRLDUURULRDDRDLLLRRDDURUDRRLDUDULRULDDLDDLDUUUULDLLULUUDDULUUDLRDRUDLURDULUDDRDRDRDDURDLURLULRUURDUDULDDLDDRUULLRDRLRRUURRDDRDUDDLRRLLDRDLUUDRRDDDUUUDLRRLDDDUDRURRDDUULUDLLLRUDDRULRLLLRDLUDUUUUURLRRUDUDDDDLRLLULLUDRDURDDULULRDRDLUDDRLURRLRRULRL",
"LDUURLLULRUURRDLDRUULRDRDDDRULDLURDDRURULLRUURRLRRLDRURRDRLUDRUUUULLDRLURDRLRUDDRDDDUURRDRRURULLLDRDRDLDUURLDRUULLDRDDRRDRDUUDLURUDDLLUUDDULDDULRDDUUDDDLRLLLULLDLUDRRLDUUDRUUDUDUURULDRRLRRDLRLURDRURURRDURDURRUDLRURURUUDURURUDRURULLLLLUDRUDUDULRLLLRDRLLRLRLRRDULRUUULURLRRLDRRRDRULRUDUURRRRULDDLRULDRRRDLDRLUDLLUDDRURLURURRLRUDLRLLRDLLDRDDLDUDRDLDDRULDDULUDDLLDURDULLDURRURRULLDRLUURURLLUDDRLRRUUDULRRLLRUDRDUURLDDLLURRDLRUURLLDRDLRUULUDURRDULUULDDLUUUDDLRRDRDUDLRUULDDDLDDRUDDD",
"DRRDRRURURUDDDRULRUDLDLDULRLDURURUUURURLURURDDDDRULUDLDDRDDUDULRUUULRDUDULURLRULRDDLDUDLDLULRULDRRLUDLLLLURUDUDLLDLDRLRUUULRDDLUURDRRDLUDUDRULRRDDRRLDUDLLDLURLRDLRUUDLDULURDDUUDDLRDLUURLDLRLRDLLRUDRDUURDDLDDLURRDDRDRURULURRLRLDURLRRUUUDDUUDRDRULRDLURLDDDRURUDRULDURUUUUDULURUDDDDUURULULDRURRDRDURUUURURLLDRDLDLRDDULDRLLDUDUDDLRLLRLRUUDLUDDULRLDLLRLUUDLLLUUDULRDULDLRRLDDDDUDDRRRDDRDDUDRLLLDLLDLLRDLDRDLUDRRRLDDRLUDLRLDRUURUDURDLRDDULRLDUUUDRLLDRLDLLDLDRRRLLULLUDDDLRUDULDDDLDRRLLRDDLDUULRDLRRLRLLRUUULLRDUDLRURRRUULLULLLRRURLRDULLLRLDUUUDDRLRLUURRLUUUDURLRDURRDUDDUDDRDDRUD"
]

print get_code(next_button_map_1, ["ULL", "RRDDD", "LURDL", "UUUUD"])
print get_code(next_button_map_1, INPUTS)


